require_relative "chess/coordinates"
require_relative "chess/board"
require_relative "chess/move"
require_relative "chess/screen"
require_relative "chess/path"

require_relative "chess/game_setup"
require_relative "chess/game"
require_relative "chess/player"

require_relative "chess/piece"
require_relative "chess/pieces/null_piece.rb"
require_relative "chess/pieces/pawn.rb"
require_relative "chess/pieces/rook.rb"
require_relative "chess/pieces/knight.rb"
require_relative "chess/pieces/bishop.rb"
require_relative "chess/pieces/queen.rb"
require_relative "chess/pieces/king.rb"
