require "yaml"

require_relative "chess/game_setup"
require_relative "chess/player"
require_relative "chess/game"
require_relative "chess/screen"

require_relative "chess/board/coordinates"
require_relative "chess/board"
require_relative "chess/board/grid"
require_relative "chess/board/move"

require_relative "chess/path"
require_relative "chess/piece"
require_relative "chess/pieces/null_piece"
require_relative "chess/pieces/pawn"
require_relative "chess/pieces/rook"
require_relative "chess/pieces/knight"
require_relative "chess/pieces/bishop"
require_relative "chess/pieces/queen"
require_relative "chess/pieces/king"
