require_relative "chess/coordinates"
require_relative "chess/board"

require_relative "chess/piece"
require_relative "chess/pieces/pawn.rb"
require_relative "chess/pieces/rook.rb"
require_relative "chess/pieces/knight.rb"
require_relative "chess/pieces/bishop.rb"
require_relative "chess/pieces/queen.rb"
require_relative "chess/pieces/king.rb"
